### PR TITLE
Speed up Travis CI run

### PR DESCRIPTION
**Pull request by aried3r**
Travis runs `bundler install` itself, but in parallel.
`cache: bundler` should speed up future CI runs.

Screenshot 2020-05-25 at 13 39 03

### CODE REVIEW

**Comment by aried3r** [comment]
Since the tests are now failing, I assume I overlooked the specific test setup needed for solargraph. 

Am I missing something here, @castwide or is there a chance this can be "fixed" (assuming something is broken to begin with)?

**Comment by castwide** [comment]
This was an issue that arose with Travis CI builds a while ago. Someone from Travis suggested removing `cache: bundler`, and that fixed it. I'm not sure what the root cause is, but part of the problem might be the hacks involved in supporting Ruby < 2.3.

**Comment by aried3r** [comment]
> Someone from Travis suggested removing cache: bundler, and that fixed it.

Hmm, I guess because caching moves the gems to `--path=${BUNDLE_PATH:-vendor/bundle}`. I'll try to have another look and will remove `cache: bundler` if necessary. The removal of the duplicate `bundle install` should still give a nice speedup.

> but part of the problem might be the hacks involved in supporting Ruby < 2.3.

I've seen #234, what is the current status of that PR? Also, which hacks are you referring to? There are [statistics](https://ecosystem.rubytogether.org/) now, sourced from RubyGems. 2.1 still seems active, but if supporting EOL Rubies means holding back solargraph it's something to consider.

**Comment by aried3r** [comment]
I think I found the changes you mentioned. https://github.com/castwide/solargraph/commit/d463297db2b1f6fc3e582febcdfeaa02811760d9

I'll try to play around a bit. Sadly I cannot reproduce this locally, so I'll create some noise here.

**Comment by castwide** [comment]
> I've seen #234, what is the current status of that PR? Also, which hacks are you referring to?

Primarily the `.travis-bundler.rb` script that selects a version of Bundler based on the Ruby version. There's some other Bundler compatibility code in the library itself, but it's less likely to have side effects.

> There are [statistics](https://ecosystem.rubytogether.org/) now, sourced from RubyGems. 2.1 still seems active, but if supporting EOL Rubies means holding back solargraph it's something to consider.

Dropping support for Ruby < 2.3 is probably inevitable. I'm not sure when it'll happen, but it might be as soon as one or two minor releases, i.e., 0.40 or 0.41.

> I'll try to play around a bit. Sadly I cannot reproduce this locally, so I'll create some noise here.

No problem. Thanks for the heads up.

**Comment by aried3r** [comment]
It seems following my changes I cannot even get the specs to work on any Ruby version. I tried being more explicit using `Bundler::Definition.build` (following [this article](https://nts.strzibny.name/working-with-bundler-from-your-ruby-code/)) but that also didn't work on Travis, while it works locally.

I didn't spend too much time on it, though and the code I wrote was pretty hacky, lacking error handling etc, but I just wanted to play around.

I'm not going to pursue this branch anymore and instead will open another PR which just removes the duplicate `bundler install` (which hopefully isn't the reason it works at all).

**Comment by gwillcox-r7** [comment]
Given Travis has now been removed with https://github.com/castwide/solargraph/pull/627 would it make sense to perhaps close this PR?

**Pull request closed without merging**
