### PR TITLE
Support rubocop 1.0

### PR DESCRIPTION
**Pull request by zaratan**
Fixes: #380

### CODE REVIEW

**Comment by zaratan** [comment]
I tried running the rubocop installed by a `bundle install` in the repository (`0.93.1`) and it screamed. So I guess it's fine to do it that way.

**Comment by jherdman** [comment]
Is there anything we can do to help get this merged and released?

**Comment by zaratan** [comment]
@castwide can me merge this ? If not, what can I do to help ?

**Comment by numbcoder** [comment]
ping @castwide

**Comment by castwide** [comment]
Sorry for the delay. I'm trying to determine whether this PR should go into master for release in 0.40.0 (might take a few days) or moved to a patch release as 0.39.18 (can happen much sooner). I'll update again shortly.

**Comment by zaratan** [comment]
@castwide I think there's no hurry to have this ASAP in master. IMO, a few days won't make any difference. Take your time.

Thank you very much for looking into it 😊

**Comment by gee-forr** [comment]
I'm totally happy with either approach. Take your time @castwide and know that we appreciate this amazing tool.

**Comment by zaratan** [comment]
I'll leave my branch around for a few days (probably until next year) so people that have a Gemfile based on it can migrate back to the normal solargraph. Thanks again @castwide ♥️

**Pull request merged**
